### ISSUE TITLE
게시글 (페이지네이션 + 정렬) 로직 버그 

### ISSUE THREAD

**Issue by sGOM** [djkeh/fastcampus-project-board#123]
latest commit [ca708c0](https://github.com/djkeh/fastcampus-project-board/commit/ca708c045a96b03784d6f28396938952ffc7eec9) 에서 수정되어 있지 않은 점을 보고 이슈 작성

[articles/index.th.xml](https://github.com/djkeh/fastcampus-project-board/tree/main/src/main/resources/templates/articles/index.th.xml) 의 `<attr sel="#pagination">` 부분의 url(href태그)에서
sort 를 유지하는 코드가 없어 `정렬 -> 페이지 변경` 시에 정렬이 사라지는 버그 발생

url에 `sort={param.sort}` 를 추가해야 될 것으로 보임

확인하고 잘못된 이슈라면 closed 해주시면 될 것 같습니다

**Comment by djkeh** [comment]
좋은 의견 감사합니다. 해당 부분은 버그가 맞습니다. 수정을 하는 것이 좋을 것 같네요.
혹시 원하신다면 직접 pr 작성을 하셔도 좋습니다.
고맙습니다.
