### ISSUE TITLE
게시판 서비스 SecurityConfig.java 스프링 3.2 버전 시큐리티 6 최신버전에서 적용하는 법

### ISSUE THREAD

**Issue by Junobee25** [djkeh/fastcampus-project-board#134]
아직 고도화 부분은 진행하기 전이고 헤로쿠 배포까지 완료했습니다.
수강 중 시큐리티, 스프링 버전이 일치하지 않아 
formLogin, anyMatcher, mvcMatcher 등 수정해야 되는 부분이 생겨, 수정 후 잘 작동된 코드입니다.

아래 공식 문서를 참고 했습니다.
https://docs.spring.io/spring-security/reference/migration-7/configuration.html#_use_the_lambda_dsl

- My Version
    - Intellij IDEA Ultimate 2023.2.5
    - Java 17
    - Gradle 8.4
    - Spring Boot 3.2.0

```@Configuration
@EnableWebSecurity
public class SecurityConfig {
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http.authorizeHttpRequests(auth -> auth
                        .requestMatchers(
                                PathRequest.toStaticResources().atCommonLocations()).permitAll()
                        .requestMatchers(
                                HttpMethod.GET,
                                "/",
                                "/articles",
                                "/articles/search-hashtag"
                        ).permitAll()
                        .anyRequest().authenticated())
                .formLogin(Customizer.withDefaults())
                .logout(logout -> logout
                        .logoutSuccessUrl("/").permitAll());
        return http.build();
    }
```

**Comment by djkeh** [comment]
좋은 의견 감사합니다. 이 코드 샘플과 레퍼런스는 스프링 부트 3, 스프링 시큐리티 6 을 사용하는 분들에게 참고가 될 것입니다.

그러나 이 코드 제안은 우리 강의 프로젝트에 적용하진 않겠습니다.
본 강의는 출시 당시 스프링 부트 2.7.0 으로 만들었다고 광고를 하고 만들어졌습니다.
지금 강의 소스코드의 부트 버전을 3으로 크게 올리면, 광고를 보고 강의를 구매하신 수강생 분들꼐서
강의 내용과 소스 코드 버전이 일치하지 않는 것 때문에 혼란에 빠지실 수 있습니다.
스프링 부트 2.7 과 시큐리티 5는 아직도 충분히 최신 버전이라 할 수 있고, `SecurityFilterChain` 빈을 등록하는 설정 방식도 이용하고 있습니다.
수강생 분들께서 현재 강의 코드로 공부를 한 후, 새로운 버전의 코드 스타일에 새로 적응하더라도 크게 어려워하진 않으실 겁니다.

본 이슈는 종료하겠습니다.
