### ISSUE TITLE
내일 할 일

### ISSUE THREAD

**Issue by djkeh** [djkeh/fastcampus-project-board#135]

**Comment by psh10066** [comment]
wow

**Comment by nomoreFt** [comment]
hello world

**Comment by withbeth** [comment]
ㅎㅇ

**Comment by FlymetDev** [comment]
안녕하세요.

**Comment by djkeh** [comment]
이 이슈는 231216 (토) 패스트캠퍼스가 주관하는 오프라인 세미나 "일할맛 2기" 에서
세미나 발표 도중 라이브 코딩을 진행하면서 연습용으로 작성하였습니다. 데모가 끝났으므로 이슈는 종료합니다.

* https://fastcampus.co.kr/category_online_devtaste
