### ISSUE TITLE
#38 해시태그 검색 페이지에서 페이징이 안되는 문제

### ISSUE THREAD

**Issue by LimdaeIl** [djkeh/fastcampus-project-board#138]
#38 학습을 마치고 찾은 이슈입니다. 글을 작성하다 보니까 너무 길어졌습니다...
**맨 아래에서 이미지로 간단하게 문제와 해결을 볼 수 있습니다.**

`http://localhost:8080/articles/search-hashtag`  페이지로 이동한 후에 찾고자 하는 `해시태그`를 선택합니다.
선택된 `해시태그`와 동일한 게시글 목록 출력까지 정상적으로 잘 수행됩니다. 
하지만 선택된 `해시태그` 페이징 처리에서 문제가 발생합니다.

문제점은 `해시태그`가 선택된 상태에서 `2` 페이지로 넘어가려고 `2` 번호를 클릭하면 찾는 게시글 목록이 모두 사라집니다.
구체적으로, `http://localhost:8080/articles` 페이지로 이동하면서 선택되었던 `해시태그`가 검색창에 `#해시태그` 로 검색을 수행합니다. `ArticleService` 에서 임시방편으로 미리 `#` 을 미리 추가한 상태이기 때문에 `#해시태그` 로 검색이 불가능한 상황입니다. 따라서 `해시태그`로 검색해야 올바른 해시태그 검색을 수행할 수 있습니다.

`ArticleService` 의 `searchArticles()` 메서드의 검색 종류에서 해시태그에 `#` 이 함께 작성된 내용입니다 :

```java
// "#" + searchKeyword 이 두 개 넣어버리는 이슈가 발생될 수 있지만, 지금은 # 을 미리 붙여서 키워드로만 검색합니다.
case HASHTAG -> articleRepository.findByHashtag("#" + searchKeyword, pageable).map(ArticleDto::from);
```

이 문제를 해결하기 위해 두 가지 방법을 생각했습니다.
1. 이동하는 것을 유지하자. 선택한 `해시태그` 페이징 처리 결과를 `http://localhost:8080/articles` 에서 정상적으로 처리되도록 수정하기
2. 굳이 이동하지 말자. `http://localhost:8080/articles/search-hashtag`  에서 정상적으로 페이징 처리되도록 수정하기

둘 중에 어느 방법으로 해야 좋을지 생각하다가, 열심히 해시태그 전용 검색 페이지를 생성했으니까 `2.` 번 방식을 선택했습니다. 해결 방법은 `search-hashtag.th.xml` 에서 `<attr sel="#pagination">` 태그 안에 `<attr>` 태그의 `th:href` 속성을 `/articles/search-hashtag` 으로 변경해주면 됩니다.

다음은 #38 의 `search-hashtag.th.xml` 를 수정하기 전의 코드입니다:
```xml
    <attr sel="#pagination">
      <attr sel="ul">
        <attr sel="li[0]/a"
              th:text="'previous'"
              th:href="@{/articles(page=${articles.number - 1}, searchType=${searchType.name}, searchValue=${param.searchValue})}"
              th:class="'page-link' + (${articles.number} <= 0 ? ' disabled' : '')"
        />
        <attr sel="li[1]" th:class="page-item" th:each="pageNumber : ${paginationBarNumbers}">
          <attr sel="a"
                th:text="${pageNumber + 1}"
                th:href="@{/articles(page=${pageNumber}, searchType=${searchType.name}, searchValue=${param.searchValue})}"
                th:class="'page-link' + (${pageNumber} == ${articles.number} ? ' disabled' : '')"
          />
        </attr>
        <attr sel="li[2]/a"
              th:text="'next'"
              th:href="@{/articles(page=${articles.number + 1}, searchType=${searchType.name}, searchValue=${param.searchValue})}"
              th:class="'page-link' + (${articles.number} >= ${articles.totalPages - 1} ? ' disabled' : '')"
        />
      </attr>
    </attr>
...
```

`search-hashtag.th.xml` 에서 `해시태그` 페이지에서 정상적인 수행을 위해 다음과 같이 수정합니다:

```xml
...
        <attr sel="#pagination">
            <attr sel="ul">
                <attr sel="li[0]/a"
                      th:text="'previous'"
                      th:href="@{/articles/search-hashtag(page=${articles.number - 1},
                       sort=${param.sort},
                       searchType=${searchType.name},
                       searchValue=${param.searchValue})}"
                      th:class="'page-link' + (${articles.number} <= 0 ? ' disabled' : '')"
                />

                <attr sel="li[1]" th:class="page-item" th:each="pageNumber : ${paginationBarNumbers}">
                    <attr sel="a"
                          th:text="${pageNumber + 1}"
                          th:href="@{/articles/search-hashtag(
                           page=${pageNumber},
                           sort=${param.sort},
                           searchType=${searchType.name},
                           searchValue=${param.searchValue})}"
                          th:class="'page-link' + (${pageNumber} == ${articles.number} ? ' disabled' : '')"
                    />
                </attr>

                <attr sel="li[2]/a"
                      th:text="'next'"
                      th:href="@{/articles/search-hashtag(page=${articles.number + 1},
                       sort=${param.sort},
                       searchType=${searchType.name},
                       searchValue=${param.searchValue})}"
                      th:class="'page-link' + (${articles.number} >= ${articles.totalPages - 1} ? ' disabled' : '')"
                />
            </attr>
        </attr>
...
```
`th:href` 속성값을 `/articles/search-hashtag` 으로 변경하기만 하면 되는 간단한 문제였습니다.  

추가적으로, #123 의 문제도 함께 해결하기 위해 `sort=${param.sort}` 를 추가했습니다. 근데, #123 에서 제가 타임리프에 대해 조금 밖에 몰라서 따라하니까 에러가 발생했습니다... 구체적으로, `$` 을 제외한 `sort={param.sort}` 를 적용하면 해당 페이지로 이동할 때, HTTP 500 에러가 발생합니다. 그래서 저는 `sort=${param.sort}` 수정하고 적용한 점을 참고하기 바랍니다.

### 1.1  `http://localhost:8080/articles/search-hashtag` 진입
```java
http://localhost:8080/articles/search-hashtag
```
![image](https://github.com/djkeh/fastcampus-project-board/assets/131642334/e610ca39-ecc6-45cf-a30a-45832e45ed3e)

### 1.2 `#spring` 해시태그 클릭
```java
http://localhost:8080/articles/search-hashtag?page=&sort=&searchType=HASHTAG&searchValue=%23spring
```
![image](https://github.com/djkeh/fastcampus-project-board/assets/131642334/8911ad4d-645f-4528-a962-987bb7428877)
![image](https://github.com/djkeh/fastcampus-project-board/assets/131642334/d241625d-ba21-40d4-8e0a-4a090ba65f8a)

### 1.3 `2`번 페이지 버튼 클릭 후 화면
```java
// 문제 발생!
http://localhost:8080/articles?page=1&sort=&searchType=HASHTAG&searchValue=%23spring
```
![image](https://github.com/djkeh/fastcampus-project-board/assets/131642334/679eb638-175e-49b4-a441-e5c62adcecde)

## 2. 해결 후의 동작
```java
// 2.1 페이지 이동 성공! 나머지 버튼도 모두 정상 동작합니다.
http://localhost:8080/articles/search-hashtag?page=1&sort=&searchType=HASHTAG&searchValue=%23spring
```
![image](https://github.com/djkeh/fastcampus-project-board/assets/131642334/01fe9f5d-533b-4310-8e9a-bd57acc3ebc7)

**Comment by djkeh** [comment]
안녕하세요? 내용이 조금 기네요. 제가 시간이 날 때 다시 한 번 찬찬히 읽어보고, 답변 드리겠습니다.
답변에 다소 시간이 걸릴 수도 있으니 양해 부탁드립니다.

고맙습니다.

**Comment by djkeh** [comment]
안녕하세요, 답신이 늦었습니다. 내용을 요약하자면 해시태그 전용 검색 페이지에서 페이징 기능의 url이 해시태그 페이지를 바라보지 않고 일반 게시판 페이지를 바라보고 있는 문제를 자세하게 리포트해주신 것 같습니다. 찾아주신 내용이 맞습니다. 추후에 이 이슈를 바탕으로 수정이 이루어지면 좋을 것 같네요. 또는 직접 이 이슈를 수정하셔서 pr을 제출해 주셔도 좋습니다.

그 밖에 해시태그를 검색하면서 겪으시는 문제는 강의의 과정 중 일부로, 강의를 후에 더 들어보시면 해시태그 구현 구조를 개선하면서 검색 기능 구현에 변화가 생기는 것을 보실 수 있으실 겁니다.

좋은 내용을 제보해 주셔서 고맙습니다.
