### ISSUE TITLE
해시태그에 대문자를 사용하여 등록 시 오류 발생

### ISSUE THREAD

**Issue by ekdh0858** [djkeh/fastcampus-project-board#142]
https://github.com/djkeh/fastcampus-project-board/assets/94153997/859f08b8-535e-4c3e-b747-c5f341d49bb2

게시글을 작성할때 #test 등록 후 #Test 등록시 오류가 발생.
해당 오류 재현시 java.sql.SQLIntegrityConstraintViolationException:Duplicate entry 'Test' for key 로그 발생.
test와 Test는 다르길 의도 했으나, 해로쿠에서 사용하는 MySQL에서는 기본적으로 대소문자 구분을 하지 않아 test 등록 후 Test등록시 오류 발생.

```
Hashtag.class
...
@Setter @Column(nullable = false) private String hashtagName; // 해시태그 이름을 나타내는 코드. 아래 내용으로 바꾸기
@Setter @Column(nullable = false, columnDefinition="varchar(255) COLLATE utf8mb4_bin") private String hashtagName;// 오류 해결한 설정을 추가한 코드 
...
```
hashtagName에 columnDefinition="varchar(255) COLLATE utf8mb4_bin" 설정을 추가해 줘서 대소문자 구분을 해 주어서 test등록 후에 Test등록 하여도 오류 발생하지 않음

**Comment by djkeh** [comment]
이 이슈는 아래 질문을 작성해주신 질문자 분께서 작성해 주셨습니다.
해시태그 기능이 대소문자를 구분하지 않아서 발생하는 문제인데,
이를 해결할 접근 방법이 한 가지가 아니기 때문에 우션 이슈를 오픈해 둡니다.

## Reference

* https://fastcampus.co.kr/qna/211368/read/24511

**Comment by djkeh** [comment]
이 이슈는 데이터베이스를 MySQL로 사용했을 때 발생할 수 있는 문제입니다. PostgreSQL로 할 때는 별다른 설정없이 테이블 문자열 컬럼이 대소문자를 구분합니다.
PostgreSQL 마이그레이션은 본 게시판 서비스 개발 강의 과정의 일부분입니다. 강의를 끝까지 듣고 만든 게시판은 PostgreSQL을 사용하므로
대소문자 이슈가 자연히 해결된 상태가 됩니다.

그러나 이슈의 내용이 좋고, 해시태그 영문자열에 대소문자 구분을 할 것인가를 정하는 정책은 서비스 운영에 필요한 디테일이라고 할 수 있습니다.
이에 패스트캠퍼스 "10개 프로젝트로 시작하는 백엔드 웹개발" 강의를 빌어 다음과 같이 정하고 작업을 진행합니다.

* 본 게시판 서비스는 대소문자 구분을 허용하지 않는 정책으로 이 문제를 해결한다. (https://github.com/djkeh/fastcampus-project-board/issues/142#issuecomment-2078118838 에서 1안 채택)
* 모든 영문 해시태그는 소문자로 저장하고, 영문 해시태그 검색은 대소문자 구분을 하지 않는다.
* 이는 해시태그의 보편적인 스펙을 따르는 결정이다.

이 이슈는 패스트캠퍼스 "10개 프로젝트로 시작하는 백엔드 웹개발" 파트8 강의의 `CH01. 14. TDD란?` 강의 클립에서 실습 내용으로 활용합니다.

## Reference

* https://en.wikipedia.org/wiki/Hashtag#Format
* https://fastcampus.co.kr/dev_online_javaspring
