### ISSUE TITLE
ch01 04 -> 05, ch02 09 -> 10 강의 관련 문의사항

### ISSUE THREAD

**Issue by riderkaman** [djkeh/fastcampus-project-board#84]
안녕하세요 강의 잘 보고 있습니다. ch02까지 보면서 개인적으로 불편했던 점 두가지가 있어 문의드립니다. 혹시 이곳에 문의드리는 게 아니라면 이슈 삭제해 주셔도 됩니다.

1. ch01 04 -> 05 넘어갈 때 생겨난 프로젝트들에 대한 설명 부재
ch01 04에서 예시로 프로젝트에 카드를 3개 정도 만들었는데, 05에서 "제가 미리 만들어 왔습니다" 하시면서 17개의 카드를 보여주십니다. 하지만 이 부분에 대해 어떤 목록이 추가되었는지에 대해 별도의 설명이나 강의자료가 없어 강의를 앞뒤로 돌려가며 무엇이 추가된 것인가 찾아봐야 하는 불편함이 있습니다.

2. ch02 09 -> 10 넘어갈 때 추가된 userAccount 관련 설명 부재
이 부분은 뭔가 강의가 통으로 빠진 느낌인데, erd에도, 도메인도, 테스트도 추가되었는데 이에 대한 강의가 보이지 않는 것 같습니다. 제가 놓친 걸수도 있는데 최소한 ch02에는 관련된 내용이 없는 것 같습니다.

읽어주셔서 감사합니다.

**Comment by djkeh** [comment]
안녕하세요, 김은호입니다. 강의 시청에 관해 의견을 주셔서 감사합니다.
하나씩 답변을 드리겠습니다.

### 1. Ch01. 04. -> 05. 로 넘어갈 때 생겨난 프로젝트들에 대한 설명 부재

정확히는 프로젝트 안에 만들어진 카드들에 관한 내용이군요. 04번 강의에서는 깃헙 프로젝트 설명 이후에 카드 만드는 법과 관리 방법을 디테일하게 설명드리고 있습니다.
이 설명 내용을 바탕으로 미리 파트2 강의의 커리큘럼 제목을 그대로 카드로 만들어서 준비해둔 상태로 05번 강의를 시작합니다.
설명을 빼놓진 않았고, 05번 강의에서 이 카드들의 내용이 무엇인지, 어떻게 만들었는지 화면과 함께 보여드리고 있습니다. `9:01 ~` 부터 찬찬히 확인해 보세요.

프로젝트 카드는 소스코드가 아니기 때문에 강의와 완전히 동일하게 가져가지 않아도 됩니다.
하지만 완전히 똑같이 따라하며 배우고 싶으실 수 있지요. 그런 경우라면 깃헙 프로젝트 화면마다 잠시 강의를 멈춰두고,
04번에서 배운 카드 만드는 법을 이용해서 화면을 보면서 카드를 똑같이 따라 만드시면 되겠습니다.
속성과 프로젝트 설정은 모두 04번 강의에서 만들어 둔 그대로이므로 카드만 새로 만드시면 됩니다.
다시 한 번 말씀드리지만 새로 작성한 카드들은 파트 2 강의 커리큘럼의 제목들입니다. 화면을 멈춰두고 보면서 따라하는게 불편하시다면
그저 강의 커리큘럼을 열어보시고, 제목을 그대로 옮기셔도 똑같이 만드실 수 있겠습니다.

어찌됐든 04번과 05번 사이에 미리 만들어 둔 카드들이 등장하니까, 혼란스러우셨던 것 같습니다.
하지만 그렇게 하는 것이 더 나은 선택이었다는 설명을 들으시면 납득이 되시리라 생각합니다.
05번 강의에서 총 17개의 카드가 만들어지고, 각 카드를 만드는 절차는 카드 제목만 빼고 완전히 동일합니다.
재차 말씀드렸듯이 무슨 제목으로 카드를 만들지도 이미 정해져 있지요. '강의 커리큘럼 제목을 그대로 카드로 옮기기' 이니까요.
이 17개의 커리큘럼 제목을 카드로 하나하나 작성하는 반복 작업을 강의 영상에 그대로 담으면서 동영상 시간을 쓰는 것은 굉장히 비효율적일 것입니다.
전체 영상의 길이는 어느 정도 가이드가 잡혀있기 때문에, 작업하는 부분을 영상으로 남기면 그 시간 만큼 설명을 할 시간이 줄어들게 됩니다.
따라서 **강의에 더 많은 내용을 담기 위해서 단순 반복 작업을 하는 부분을 생략한 것**입니다.
04번 영상에서 카드 만드는 법을 자세히 알려드리고, 05번에서 부연설명과 함께 미리 카드 17개를 준비해서 보여드리는 방법을 택하였습니다.

### 2. ch02 09 -> 10 넘어갈 때 추가된 userAccount 관련 설명 부재

Ch02. 10번 강의 `5:11`부터 강의를 들어보세요. `UserAccount`가 어떻게, 왜 추가되었는지 알 수 있습니다.
이 강의는 2가지 이유로 이렇게 꾸며졌습니다.

1. 위와 같은 이유입니다. **만드는 과정을 담을 수록, 설명 시간이 줄어듭니다.** 한정된 강의 시간 안에 더 많이 배우실 수 있도록, 더 많이 내용을 담아드리고 싶었습니다.
    - `UserAccount`를 미리 준비해서 보여줘도 좋다고 판단하는 기준은, "동일한 방법을 강의에서 이미 자세히 설명하였는가" 로 합니다.
    - `UserAccount` 엔티티를 만드는 방법은 앞선 강의 중 도메인 설계와 데이터베이스 접근 로직 구현에서 `Article`, `ArticleComment` 로 소개해 드리고 있습니다.
    - `Article`, `ArticleComment` 에서 JPA를 이해하고 엔티티와 repository를 작성하는 방법을 익혔으므로, `UserAccount`도 만들 수 있습니다.
    - 실제로 어떻게 만들어졌는지를 pr #17 로 자세히 확인하실 수 있습니다.
2. 한 가지 더 중요한 이유가 있는데, **실무에서 여러 개발자와 협업하는 과정을 시뮬레이션하고 중간 과정을 이해하고 해결하는 과정을 수강생 분들에게 보여드리기 위함입니다.**
    - 2번 의견을 주시면서 느끼셨던 "설명이 통으로 빠진 느낌" 이 제가 이 강의에서 그대로 의도한 부분입니다.
    - `UserAccount`를 만드는 방법(엔티티 만드는 법)은 앞서 설명드렸으므로, 내가 아닌 다른 사람이 `UserAccount`를 만들고 내가 그것을 모르고 있다가 발견한 상황을 연출한 것입니다.
    - 그리고 이를 시청하시는 수강생 분들과 함께 follow-up 하고 내용을 이해해 나가는 과정을 강의로 담았습니다.
    - 실무에서 그러한 일들이 수시로 일어납니다. 때문에 이런 설명의 부재를 해결하기 위해서 수시로 스크럼이나 회의를 하면서 서로 싱크를 맞추지요?
    - 그러나 사람 대 사람으로 회의를 하지 않아도, 잘 작성된 커밋들과 깃헙 시스템으로 follow-up 이 가능하다는 것을 강의로 보여드리고 있는 것입니다. `5:11`부터 천천히 설명을 들어보세요.
    - 여기서 pr 을 merge 하는 2가지 방법(merge, rebase)과 그 차이도 함께 설명드리고 있습니다.
    - 실제로 이 부분이 실전적이어서 마음에 든다는 피드백을 주신 수강생 분들이 많으세요.

강의 시청에 관해 의견을 주셔서 다시금 감사드립니다.
강의를 들으시다가 또 어려운 점이 생기면 강의의 질문 게시판을 이용해 주시기 바랍니다.
이번 패스트캠퍼스 강의부터 아래와 같이 질문 게시판 서비스를 시작해서 수강생 분들의 질문에 대답을 드리고 있습니다.

https://fastcampus.co.kr/qna/211368/1

이는 강의 화면 우상단 `Q&A` 버튼으로 접근 가능합니다.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/4949544/190377018-304af753-22bf-439f-8158-264d70e2e72e.png">

고맙습니다.

**Comment by riderkaman** [comment]
상세한 답변 감사드립니다. 앞으로는 Q&A에 문의드리도록 하겠습니다.
1. 제가 놓친 부분이 있는 것 같습니다.
2. 강사님의 설명에도 불구하고, 그 "뜬금없음"이 의도라는 말씀에는 납득하기 어렵습니다. 해당 강의의 토픽명이 '로그인 페이지 만들기' 이기 때문입니다.
해당 강의의 절반 가까이 rebase 관련 토픽명과 상관없는 내용이 나오는 것이 수강자들에게 혼란을 가져다 줄 수 있다고 생각합니다.
개인적으로는 erd는 빠르게 만들고 넘어가고, 소스는 복붙한 후(어디서 복붙해야 하는지는 알려주셔야 합니다) 특기할 만한 토픽에 대한 설명이 이루어진 후, 별도의 토픽으로 rebase 관련 내용을 강의해주셔도 좋을 것 같습니다.

다시한번 상세한 설명과 좋은 강의 감사드리고, 앞으로는 Q&A에 문의드릴테니 이 이슈는 바로 닫아주셔도 됩니다.

**Comment by djkeh** [comment]
답변 잘 읽었습니다. 강의 내용이 좀 더 강의 주제에 부합하는 설명들로 채워지면 좋겠다는 말씀에 공감합니다.
erd 를 작성하는 비중을 조금 더 줄이고 코드의 작성과 설명 분량이 더 많았으면 한다는 의견도 추후 강의 제작에 더 반영될 수 있도록 하겠습니다.

`UserAccount`와 인증 기능의 구현은 이어지는 CH03. 세부 기능 구현 챕터에서
`로그인 페이지 기능 테스트 정의`, `로그인 페이지 기능 구현`, `인증 기능 구현` 강의로 설명드리고 있으니 차근차근 강의를 들으시면서 학습해 나가시면 좋을 것 같고요,
`로그인 페이지 만들기` 강의 안에서는 크게 중요하지 않은 `UserAccount`의 설명을 세세하게 해드리지 않은 것,
`로그인 페이지 만들기` 강의에서 깃을 다루는 내용이 많이 들어있는 것,
로그인 페이지를 만드는데는 직접적인 연관이 없는 `UserAccount` 변경점을 `로그인 페이지 만들기`에서 다루는 것 모두 의도한 것입니다.

그러면 `로그인 페이지 만들기`가 아니고 `깃으로 협업하기`, `리베이스 하는 법` 같이 더 적절한 강의 제목이 있지 않았을까 의아하실 것 같은데요,
제가 이번 프로젝트 강의에서 `로그인 페이지 만들기`에 `UserAccount` 설명을 하지 않고 리베이스가 들어가는게 왜 적절하다고 생각하고,
`로그인 페이지 만들기` 안에서는 설명을 드리지 않지만 `UserAccount`가 이 시점에 나오는 것은 필요하다고 생각하고,
그게 어떻게 수강생 분들께 도움을 드렸으면 좋겠다고 생각했는지, 그 의도를 구체적으로 납득이 가실 수 있을 만큼 충분히 설명드리고 싶습니다만,
아무리 그런 설명을 장황하게 드려도 결과적으로 강의 내용과 의도가 잘 전달되지 않아 불편을 겪으신 것은 변하지 않는다고 저는 생각합니다.
저는 그 강의에서 협업 상황과 깃을 사용하는 자세한 과정을 담은 것을 후회하지는 않습니다만,
앞으로는 좀 더 불편감 없이 공감하며 들을 수 있는 강의를 만들 수 있도록 계속 고민하고 노력하겠습니다.
우선은 강의를 차분히 들어보시고, 여전히 설명이 필요하다 느껴지는 부분이 생기면 질문 게시판을 통해 소통을 하면 좋을 것 같습니다.

고맙습니다.
